[package]
name = "kuala/valobox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Red = "uncontained0/red@1.2.2"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.5.0"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.0.0"
TableUtil = "sleitnick/table-util@1.2.0"
Reflex = "littensy/reflex@4.2.0"